# Travis CI configuration.

notifications:
  email:
    on_success: change # [always|never|change]
    on_failure: change # [always|never|change]

# Test on Ubuntu 14.04 Trusty and macOS 10.13.
os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode9.3

# Use a base Python language.
# Note that this does not affect osx. We use brew's python on osx.
language: java

# Do not try and clone submodules. The ./configure script will do that.
git:
  submodules: false

before_install:
  # Install python3.6 on macOS. Note that an outdated brew python package is
  # already installed, so we must use the upgrade command.
  - if [[ "$(uname)" == "Darwin" ]]; then export OSX=1; else export LINUX=1; fi
  - test -z $OSX || brew update
  - test -z $OSX || brew upgrade python

script:
  - ./configure --noninteractive
  - test -f bootstrap.sh
  # - bazel query --local_resources=400,1,1.0 //...
